# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
    - 2.7
    - 3.5
    - 3.6

before_install:
  - ls
  - pwd
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
    # Pull down a miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

    # Build out the environment
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

    # swig: for building CCTools
    # future: for builtins
    
  - conda create -q -n forcebalance_env python=$TRAVIS_PYTHON_VERSION numpy scipy lxml networkx swig future
  - source activate forcebalance_env

    # Add conda-forge and omnia to your channel list
  - conda config --add channels omnia --add channels conda-forge
  
    # Update to conda-forge versions of packages
  - conda update --yes --all

    # Omnia packages
  - conda install -c omnia pymbar openmm

    # Gromacs (from Bioconda)
  - env
  - conda install -c bioconda gromacs
  - . $HOME/miniconda/pkgs/gromacs-4.6.5-0/bin/GMXRC.bash
  
    # Tinker binaries
  - wget https://dasher.wustl.edu/tinker/downloads/bin-linux64-8.2.1.tar.gz -O tinker.tar.gz
  - tar xvzf tinker.tar.gz
  - mkdir -p $HOME/opt/tinker
  - mv bin-linux64 $HOME/opt/tinker/bin
  - export PATH="$HOME/opt/tinker/bin:$PATH"

    # Amber
  - conda install -c ambermd ambertools

    # Install anything not in conda
  # - pip install pint
  - pip install codecov
  # - pip install pytest-cov
  # - conda list

    # Install ForceBalance
  - python setup.py install

before_script:
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'
  # - pip install -e .

script:
  - python test
  # - py.test -v --cov=eex/ --durations=5

notifications:
  email: false

after_success:
  - codecov
