# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
    - 2.7
    - 3.5
    - 3.6

before_install:
  - ls
  - pwd
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
    # Pull down a miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

    # Build out the environment
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n forcebalance_env python=$TRAVIS_PYTHON_VERSION numpy scipy lxml networkx
  - source activate forcebalance_env

    # Omnia packages
  - conda install -c omnia pymbar openmm

    # Gromacs (from Beckstein lab)
  - conda install -c becksteinlab gromacs-2016
  
    # Tinker binaries
  - wget https://dasher.wustl.edu/tinker/downloads/bin-linux64-8.2.1.tar.gz -O tinker.tar.gz
  - tar xvzf tinker.tar.gz
  - ls $PWD/tinker/bin
  - export PATH="$PWD/tinker/bin:$PATH"

    # Amber
  - conda install -c ambermd ambertools

  - python setup.py install
    # Install anything not in conda
  # - pip install pint
  # - pip install codecov
  # - pip install pytest-cov
  # - conda list

before_script:
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'
  # - pip install -e .

script:
  - python test
  # - py.test -v --cov=eex/ --durations=5

notifications:
  email: false

after_success:
  - codecov
